spring:
  application:
    name: vector-search-demo

  spring:
    ai:
      ollama:
        embedding:
          base-url: http://localhost:11434
          model: nomic-embed-text

  data:
    mongodb:
      uri: mongodb+srv://dev:dev@cluster0.wmish1q.mongodb.net/sample_mflix

  app:
    create-embedding-enabled: true

server:
  port: 8080
